name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: resume.pdf
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: build
        uses: github-actions-x/hugo@master
      - name: push
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          push-branch: 'master'
          commit-message: 'resume update'
          force-add: 'true'
          files: resume.pdf
          name: tabVersion
          email: tabvision@bupt.icu
          
